import asyncio
import json
import time
import logging
from typing import Dict, Any, Optional
from core.security import SEC_KERNEL
from core.hal import HAL
from core.loader import KERNEL_LOADER

# Setup Network Logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s [%(levelname)s] NET_NODE: %(message)s',
    handlers=[logging.FileHandler("sys_kernel.log"), logging.StreamHandler()]
)

class DistributedNode:
    """
    ASYNCHRONOUS PSEUDO-ARCH NETWORK LAYER.
    Handles non-blocking Node-to-Node command routing with TTL Tokens 
    and AES-GCM payloads.
    """
    def __init__(self, host: str = '127.0.0.1', port: int = 9001):
        self.host = host
        self.port = port
        self.node_id = f"node_{int(time.time())}"
        self._server: Optional[asyncio.Server] = None
        self._is_running = False

    async def _process_inbound(self, reader: asyncio.StreamReader, writer: asyncio.StreamWriter):
        """
        ASYNC INBOUND HANDLER:
        Strict authentication, decryption, execution, and memory zeroing.
        """
        addr = writer.get_extra_info('peername')
        logging.info(f"Incoming connection from {addr}")

        try:
            # 1. RECEIVE & PROTOCOL CHECK
            # Wait for data with a timeout to prevent 'Slowloris' attacks
            raw_data = await asyncio.wait_for(reader.read(4096), timeout=5.0)
            if not raw_data:
                return

            packet = json.loads(raw_data.decode())
            
            # 2. ASSERTION: SECURITY GATE
            # Validates the 15-minute short-lived token generated by SEC_KERNEL
            token = packet.get("token")
            if not SEC_KERNEL.validate_token(token):
                raise PermissionError("ERR_INVALID_OR_EXPIRED_TOKEN")
            
            # 3. DECRYPT PAYLOAD
            # Command arrives as an AES-GCM hex string
            encrypted_payload = bytes.fromhex(packet["payload"])
            decrypted_cmd = SEC_KERNEL.decrypt_field(encrypted_payload)
            
            # 4. EXECUTION IN SANDBOX
            cmd_parts = decrypted_cmd.split()
            cmd_name = cmd_parts[0]
            cmd_args = cmd_parts[1:]
            
            # Inject Hardware Context + Remote Origin Flag
            context = {"health": HAL.get_health_report(), "origin": f"remote@{addr}"}
            result = KERNEL_LOADER.dispatch(cmd_name, context, *cmd_args)
            
            # 5. ENCRYPTED RESPONSE
            # Never send raw results over the wire
            response_payload = SEC_KERNEL.encrypt_field(str(result)).hex()
            response_packet = json.dumps({"status": "OK", "data": response_payload})
            
            writer.write(response_packet.encode())
            await writer.drain()

            # 6. MEMORY SCAVENGING
            # Immediately scrub the command from RAM to prevent heap-dumps
            SEC_KERNEL._wipe_memory(decrypted_cmd)

        except (PermissionError, AssertionError) as ae:
            logging.error(f"Security Violation from {addr}: {ae}")
            writer.write(json.dumps({"status": "DENIED", "msg": str(ae)}).encode())
            await writer.drain()
        except asyncio.TimeoutError:
            logging.warning(f"Connection timeout from {addr}")
        except Exception as e:
            logging.error(f"Network Fault with {addr}: {e}")
        finally:
            writer.close()
            await writer.wait_closed()

    async def start_node(self):
        """
        Initializes the Asynchronous TCP Server.
        Must be awaited in the main kernel event loop.
        """
        self._server = await asyncio.start_server(self._process_inbound, self.host, self.port)
        self._is_running = True
        
        addr = self._server.sockets[0].getsockname()
        logging.info(f"Distributed Node Online: {addr} [ID: {self.node_id}]")

        async with self._server:
            await self._server.serve_forever()

    async def send_remote_cmd(self, target_host: str, target_port: int, token: str, command: str):
        """
        ASYNC CLIENT METHOD:
        Sends an encrypted command to a remote peer and awaits the response.
        """
        try:
            reader, writer = await asyncio.wait_for(
                asyncio.open_connection(target_host, target_port), timeout=5.0
            )

            # Encrypt Command (AES-GCM)
            encrypted_cmd = SEC_KERNEL.encrypt_field(command).hex()
            packet = {
                "token": token,
                "payload": encrypted_cmd
            }

            writer.write(json.dumps(packet).encode())
            await writer.drain()

            # Await Decrypted Response
            resp_raw = await reader.read(4096)
            resp_json = json.loads(resp_raw.decode())

            writer.close()
            await writer.wait_closed()

            if resp_json.get("status") == "OK":
                decrypted_resp = SEC_KERNEL.decrypt_field(bytes.fromhex(resp_json["data"]))
                return decrypted_resp
            
            return f"Remote Node Denied Access: {resp_json.get('msg', 'Unknown')}"

        except Exception as e:
            return f"Node Outbound Failure: {e}"

# Global Network Node Context
NETWORK_NODE = DistributedNode()